apt:
	echo "./apt-common.sh"
apt-work:
	echo "./apt-other.sh"
spotify:
	echo "./apt-spotify.sh"
usr-dirs:
	echo "Creating dirs"
	mkdir -p ~/usr
	mkdir -p ~/usr/local/bin
	mkdir -p ~/usr/local/lib
	mkdir -p ~/usr/local/share
usr: usr-dirs
	./usr.sh	
