apt:
	echo "./apt-common.sh"
apt-work:
	echo "./apt-other.sh"
spotify:
	echo "./apt-spotify.sh"
usr-dirs:
	echo "Creating dirs"
	mkdir -p ~/usr
	mkdir -p ~/usr/local
	mkdir -p ~/usr/local/bin
usr-lib:
	
usr-all: usr-dirs apt
